### PR TITLE
Publish through Github Packages

### PR DESCRIPTION
**Pull request by stephen-bunn**
As part of us starting to serve packages through Github packages, we need the scope `@groveco` to be served by a single NPM registry. Currently, we publish `@groveco/backbone.store` through the npmjs.org registry. We should start publishing this package through our Github organization's package registry.

The following changes add a basic `publishConfig` to the `package.json` that indicates where this package should be published to. Publishing this package depends on you having the appropriate `.npmrc` configuration setup (see https://github.com/groveco/skylight#usage for info).

Following the approval and merge of this package, we need to actually publish the current version of `backbone.store` to Github packages:

1. Tag and release the current version (0.5.1)
2. `npm publish` the current version
3. Update the dependency in `@groveco/grove`

**As this package is still published to NPM (v0.4.2), we should not be breaking any existing build pipelines.**

---

Currently blocked by the following items:

- [x] I've created a DSD ticket to get a `NPM_GITHUB_REGISTRY_ACCESS_TOKEN` defined in this project's CircleCI environment so we can publish to GitHub Packages using the same job. https://groveco.atlassian.net/servicedesk/customer/portal/6/DSD-1671?created=true

### CODE REVIEW

**Comment by jessewagstaff** [comment]
Would this impact publishing to https://www.npmjs.com/package/@groveco/backbone.store in any way?
It currently happens within the CircleCI config which calls`npm publish --access public`

**Comment by stephen-bunn** [comment]
> Would this impact publishing to [npmjs.com/package/@groveco/backbone.store](https://www.npmjs.com/package/@groveco/backbone.store) in any way? It currently happens within the CircleCI config which calls`npm publish --access public`

From their documentation `--access public` only affects visibility within the registry (not the registry itself). My assumption is that this command will still publish the package but to the given `publishConfig.registry`.

Thanks for pointing out the Circle CI job though.
If we want to automate publishing to the Github Packages registry, we will also need to update the config they write in that job.

The question I still have is "do we still want to publish `@groveco/backbone.store` to NPM". IMO I would prefer that we just start publishing our internal packages through an internal registry. I know we've _open-sourced_ this library in NPM... but we don't really maintain and improve on it.

**Review by peltzergrove — DISMISSED** [review]

**Review by jessewagstaff — APPROVED** [review]

**Review by brooksRoley — APPROVED** [review]

**Review by jessewagstaff — APPROVED** [review]
Thanks for the updated readme. Did you ever find out how many third party packages are using Backbone.store through npm besides Grove?

**Comment by stephen-bunn** [comment]
> Thanks for the updated readme. Did you ever find out how many third party packages are using Backbone.store through npm besides Grove?

Based on details from NPM, we have 0 dependents published within NPM.
This doesn't mean people cannot install `@groveco/backbone.store` and have it within their dependencies. For that reason, we are not removing the package from NPM. Instead, we are just archiving the project at the current version.

**Comment by stephen-bunn** [comment]
I've noticed that we are tagging versions incorrectly in this repo.
I'm planning on just doing a v1 release here as well from the latest working tag to avoid future confusion.
image

**Pull request merged**
