### PR TITLE
Circleci set GitHub user

### PR DESCRIPTION
**Pull request by icunningham88**
So it appears that setting the author within the commit isn't sufficient for circleci to push docs to our `gh-pages` branch. We also need to set a user name and email:

https://circleci.com/gh/groveco/backbone.store/532

Hopefully this is the final piece that we need to start consistently publishing documentation.

### CODE REVIEW

**Comment by icunningham88** [comment]
@al-the-x is currently in the process of testing this locally. We maybe creating another branch for this.

**Comment by icunningham88** [comment]
After @al-the-x vetting, we're sticking with this branch. We initially tested this locally with the `circleci-cli` tool, but were unable get `git` steps to work properly. This was most likely due to conflicts between the ssh key set for the CircleCi build and a user's local ssh key. We were able to test this within the CircleCi server here:

https://circleci.com/gh/groveco/backbone.store/557

And the changes worked.

**Comment by al-the-x** [comment]
Squash that typo commit and you'll get my 👍

**Comment by icunningham88** [comment]
> Squash that typo commit and you'll get my 👍

Squashed

**Pull request merged**
