### PR TITLE
Add HttpAdapterFactory to invoke HttpAdapter instances of FetchHttpAdapter or JQueryHttpAdapter

### PR DESCRIPTION
**Pull request by AtofStryker**
# Why 
For more information on:

Why fetch was chosen for the new http adapter, please see #62 and #63
For RFC discussion and proposal, please see #64

## Strategy

The `HttpAdapter` has been broken out into multiple instances. These instances include `JQueryAjaxHttpAdapter` and the newly added `FetchHttpAdapter`. Since both of these adapters share common functionality, common methods have been extracted into a base `HttpAdapter` class to provide base functionality without duplication. This allows the `JQueryAjaxHttpAdapter` and the `FetchHttpAdapter` to implement only a few methods that are specific only to their underlying technological implementations while sharing the same public API.

We will expose creation of these adapters via a factory, since `JQueryAjaxHttpAdapter` and `FetchHttpAdapter` both share the same public API and are instances of `HttpAdapter`. Both adapters can take a `headers` object in construction, as well as a callback function called `addHeadersBeforeRequest()` that will allow the user to return a headers object that needs to be dynamically calculated before each request.

An example of the factory implementation is below. The default adapter is `JQueryAjaxHttpAdapter` unless `'fetch'` is passed in as the adapter option: 
```
import {
  Store,
  HttpAdapterFactory
} from '@groveco/backbone.store';

const adapter = HttpAdapterFactory.instance({

  adapter: 'fetch' | undefined,

  urlPrefix: '/my-prefix',

  headers: {

    'static-header-1': 1

    'static-header-2': 2

  },

  addHeadersBeforeRequest() {

    const headers = {

      'dynamic-header-1': Foo()

      'dynamic-header-2': Bar()

    };

    return headers

  }

});

const store = new Store(adapter);

```

An example of direct request consumption is below:
```
try {

  const store = getStoreInstance()

  const args = await store.request('/api/login/', {

    method: 'GET' | 'POST' | 'PUT' | 'DELETE',

    headers: {

      'Content-Type': 'application/json'

    },

    data: {

      prop1,

      prop2

    }

  });

  // Do something with the successful request

} catch (e) {

  // Do something with the failed request

}
```
#### Creating a `HttpAdapter` via a Factory Pattern vs Direct Invocation 
Since multiple adapters are now present, consumers cannot invoke a new instance of a `HttpAdapter` directly. To create a new instance, consumers must use the `HttpAdapterFactory`

#### Exposing `headers` option via `HttpAdapter` constructor
Previously, consumers of this package were setting global headers via `$.ajaxSetup`. Since `$.ajax` is no longer the only implementation of the `HttpAdapter`, another method for exposing static headers was needed.

####  `request` method added to public API  via `Store` -> `HttpAdapter`
To allow for support to make generic requests that do not use the store indirectly, the decision to add a public `request` method was invoked. This allows for users to make requests directly through the `Store` The `Store`  proxies to the `HttpAdapter`, allowing for a generic method to make any request a user sees fit.

#### `addHeadersBeforeRequest` callback added
Similar to the reasons behind exposing the `headers` options, another method for exposing dynamic headers was needed. Initially, this function was going to be called `OnBeforeRequest`. Due to only limiting the consumer to set headers (dynamic or static) before each request, a rename of the function was in order to properly identify its purpose
	
#### Moving `serializeRequest` and `buildUrl` to base class

Moving `serializeRequest` functionality to its own function within a base class allows for the same logic to be shared by multiple adapters. This makes the logic easier to test and helps guarantee the behavior is the same between adapters. Same goes for `buildUrl`.

#### Adding `isInternal` argument to `_makeRequest`
Due to some existing conditions around potential `dataType` bugs within jQuery's ajax handler, `isInternal` was added to the method signature of `_makeRequest` to keep existing behavior consistent. This change might not be necessary, but wanted to allow for the least change possible within the implementation to prevent potential issues.

#### Default `application/vnd.api+json` header arguments in `_http`
Adding `application/vnd.api+json` to the default implementation of `_http` allows for all pre existing calls to `_http` to behave the same, ensuring existing legacy behavior. 

Since this is a default argument, we leverage `request` to override the default headers implementation within `_http` to allow for generic requests without predefined behavior.

#### Add `FetchAdapterError` in `FetchHttpAdapter`
Adding a new error class, such as `FetchAdapterError` , will allow us to more easily trace logging tools to see if this error has been thrown or called to help identify potential problems with the `FetchHttpAdater`

#### Add `_requestDecorator` in `JQueryAjaxHttpAdapter`
`_requestDecorator` uses `$.ajax`'s `beforeSend` method to dynamically add the headers that have been traditionally provided by `$.ajaxSetup` within the consuming app. When the consumer provides default `headers` or `addHeadersBeforeRequest()` within the construction, this method is responsible for adding these headers to the request.

### Is the public API the same? 
In short, yes. Methods have not been removed and all methods should function the same. The only public API options added are `request` and contructor options for `headers` and `addHeadersBeforeRequest`

### Can I just use the old adapter?
Yes! Just do not add add the `adapter` option and the old adapter with be returned

### What if something goes wrong?
To prevent a giant cut over at once, we can use `Optimizely` to drive an experiment to slowly migrate users over to the `FetchHttpAdapter`. If the experiment was not successful, we can always pull the plug and go back to the drawing board. 

Since there was significant refactor within the `jQueryAjaxHttpAdapter`, there is some risk involved that the default implementation did not break anything. We may want to implement a custom error class for the `jQueryAjaxHttpAdapter` to make tracing Sentry easier in case problems arise

### Are Backbone Collections behind the scenes using our default headers
This is a question I will need help addressing. It's not a lot of work to address but something we needs to be aware. Is this something you would be willing to help me address @jessewagstaff?

### Will the new `request` method use the the default `headers` and `addHeadersBeforeRequest()` 
Yes, since this would mimic the currently implementation via `$.ajaxSetup`

### There are quite a few changes here. This is a lot to review at one time!
I have broken this PR into two PRs
1) reworking the `HttpAdapter` for extension #66 
2) adding the `FetchHttpAdapter` #67 

I highly recommend stepping through the commit history to see what changed and when.

### This is a unnecessary abrupt change that we do not need right now

This is potentially the case. Though our long term goal is to move away from jQuery, it might not be a great idea in the short term. If we decide this is not a good idea to move forward with right now, we can put this whole thing 'on ice' until we are ready to tackle it again

### Other notes

- this change will require us to use the following:
	- `whatwg-fetch` Polyfill
	- `core-js@3`
	- Babel 7 (for `corejs@3`)

If having access the the [groveco](https://github.com/groveco/grove/compare/feature/http-adapter?expand=1) repo, here is an example branch as to what the new code would look like

### CODE REVIEW

**Comment by racoleman** [comment]
> If this is found to be the case, we can break this PR into two cases
reworking the HttpAdapter for extension
adding the FetchHttpAdapter

I recommend being eager with PR splitting. If you already know how you would break it up, why wait for someone to ask you to do so?

**Comment by AtofStryker** [comment]
@racoleman I wasn't too sure on the consensus to be honest, so figured I would go with the main PR to see how it was received. I will break it up into two PRs, with this being the main reference (same commit history)

**Comment by AtofStryker** [comment]
I have broken this PR into two PRs

reworking the HttpAdapter for extension #66
adding the FetchHttpAdapter #67
I highly recommend stepping through the commit history to see what changed and when.

I don't think I can get it much leaner than this. I can move the jest upgrade into its own PR to make #66 leaner, but I think that is about it.

**Comment by AtofStryker** [comment]
Closing due to lack of involvement from reviewers

**Pull request closed without merging**
