### PR TITLE
Bump to version 0.5.1

### PR DESCRIPTION
**Pull request by stephenmcrowe**
## Description
I had some troubles with publishing correctly, so this a replica of https://github.com/groveco/backbone.store/pull/82. 

`npm version` followed by `npm publish` doesn't work for some reason; I believe we don't have those `preversion`, `version`, and `postversion` scripts specified in our package.json. This causes the checkout of the tag to fail within CircleCI. 

We **DO**, however, have hooks set up within CircleCI to pick up the latest tag and publish the version. So steps I took to publish it via CircleCI.
1. Checkout new branch.
2. Manually modify the version in `package.json`
3. Git add, commit, and push.
4. Add an annotated git tag following the correct format: `git tag -a v0.5.1 -m "Version 0.5.1"`
5. Push the tag to remote. `git push origin --tags`
6. Follow CircleCI and make sure it publishes successfully. Verify the [latest version](https://www.npmjs.com/package/@groveco/backbone.store).

### CODE REVIEW

**Comment by stephenmcrowe** [comment]
Thoughts on the above steps? Anyone more familiar with the "_correct_" way to publish?

**Review by electrachong — APPROVED** [review]
It looks like 0.5.1 came through fine. I'm not familiar with how it's intended to publish new versions of backbone.store to npm. I'm guessing this might be slightly more proper sequence:

1. Make changes in a new branch to merge to master.
2. If intending to publish the changes in a new version, bump the version in package.json in that pr or a separate pr and merge to master.
3. Following approval and merge, push the annotated tag to remote.
4. Follow CircleCI and make sure it publishes successfully.

Does CI only pick up the new tag when running the pipeline for a push to a branch, or will it pick it up as long as the tag is pushed?

**Comment by stephenmcrowe** [comment]
I believe it will pick it whenever a new tag is pushed. So yes, I agree that the tag should only be pushed when the appropriate PR is merged to master. That way master reflects the latest tag.

**Review by jlejowett — APPROVED** [review]
Approved! 🎉

**Review by jessewagstaff — APPROVED** [review]

**Pull request merged**
