### PR TITLE
RFC proposal commit to convert $.ajax in http adapter to native fetch

### PR DESCRIPTION
**Pull request by AtofStryker**
## Why

In short, we want to migrate away from jQuery as we move into the future. Please see #62 and #63 for reasons behind this, as well as previous conversations.

Before we dive down this rabbit hole any further, we should really discuss what we want to do in the new implementation to make sure the best possible solution is achieved to fit our needs.

### Will all the old adapter methods be supported?

In short, yes. The API for both Http Adapters will be the same, except the fetch implementation will be an extension of the old adapter via construction/methods.

### Possible idea of `http` being a part of the public API

Currently, within the main app, there are 3 requests that use $.ajax without going through the http adapter. The requests are in following modules:

- login
- careers
- credit-card

I recommend we do one of the following

- Option 1: Have these modules use the already provided methods through the http adapter. This will allow for cross compatibility between the two adapters
- Option 2: Since some of these methods are a bit more complicated and likely wouldnt work with the provided method, we might want to make the `http` method as part of the public API. In the interim, we can have the new implementation go through the old `$.ajax` methods for stability, while using `http` for the new ones. This will require some refactoring of some of the defaults within the method (headers), but should be relatively straighforward
- Option 3: `Any other option that is better and recommended`

### Why supply a OnBeforeRequest function

Currently, `$.ajax` has a setup function that provides global setup to the `$.ajax` function. `OnBeforeRequest` allows us to do essentially the same thing. We give access to the xhr/fetch options so the method can mutate the object as needed. This would provide the same consistency to what we are used to while migrating away from jQuery

###  Testing strategy

For the module itself, we will use Jest mocks to mock the behavior of the sinon server. This will guarantee the behavior is the same as the previous implementation

## Migration/Mitigation Strategy

We will implement 2 versions of the http adapter:

- 1: The `$.ajax` adapter in its current format
- 2: The new `fetch` based adapter

In the main app, we will use experiments to drive which adapter should be turned on. This will allow us to have SOME traffic use the new adapter without sacrificing the entire integrity of the site if errors arise

### What if something goes wrong?

I recommend that within the new adapter, we implement a custom error class to have better tracing within our Sentry logs. If the adapter turns out to have issues, we can find it here and terminate the experiment so we can cut our losses

### This is a unnecessary abrupt change that we do not need right now

This is potentially the case. Though our long term goal is to move away from jQuery, it might not be a great idea in the short term. If we decide this is not a good idea to move forward with right now, we can put this whole thing 'on ice' until we are ready to tackle it again

#### Implementation example in the main app

```js
import { FetchHttpAdapter, jQueryAjaxHttpAdapter } from '@groveco/backbone.store';

let adapter

//usingNewAdapter will be driven by a experiment in the interim until we can prove its efficacy
if(usingNewAdapter){
  adapter = new FetchHttpAdapter({
        urlPrefix: '/api',
	headers: {
	    'X-Client-Version': window.CLIENT_VERSION,
	    'X-Style-Version': window.STYLE_VERSION
	},
	onBeforeRequest(request){
	  // Gives the user access to the request object to mutate if needed [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Syntax)
	  // It is recommended to use the provided Types/Interfaces provided natively by fetch
	  request.header['some-calulated-header'] = new value()

          //or
          request.headers.append("some-calculated-header", new value())

	}
   });
} else {
  adapter = new jQueryAjaxHttpAdapter({
       urlPrefix: '/api'
  })
  $.ajaxSetup({
       beforeSend(xhr) {}
  })
}

// implement a single instance for the main app to consume (similar to a singleton)
export default adapter

```

```js
import HttpAdapterInstance from '@/path/to/adapter'

// pass the implementation into the store, regardless of implementation
const store = new Store(HttpAdapterInstance);
```

```js
// login
// careers
// credit-card
import HttpAdapterInstance from '@/path/to/adapter';

// use methods without raw $.ajax to be compatible with either version
// For stability, I highly recommend to drive this with an experiment
if(usingNewAdapter){
   await HttpAdapterInstance.http("/my/url", options)
}else{
   //use previous $ajax method for stability
}
```

### Other notes

- this change will require us to use the following:
	- `whatwg-fetch` Polyfill
	- `core-js@3`
	- Babel 7 (for `corejs@3`)

The if/else statements are only temporary in the code until the experiment is a success. Once proven successful, the conditional code can be removed.

### CODE REVIEW

**Comment by AtofStryker** [comment]
Please don't mind my terrible MD formatting skillzzz

**Comment by JohnColanduoni** [comment]
Why would we make `makeRequest` public, as opposed to what is called `_http` in the PR? The former is more high-level and it sidesteps the `serializeRequests` refactor.

**Comment by jessewagstaff** [comment]
I don't think we should make `makeRequest` public. The 3 places that use $.ajax without going through the http adapter do this because they are calling legacy API endpoints that are not compatible with the JSON:API spec and thus `backbone.store`. There are even uses of $.ajax hidden behind Backbone. Do a search through all *.js for `url: '`

**Comment by AtofStryker** [comment]
@JohnColanduoni updated RFC for request to make http method public

**Comment by AtofStryker** [comment]
@jessewagstaff I do like John's idea of making `http` public. We should be able to make the requests via the http method through the http adapter to do our default handling without using the rest of the store. It would work to remove $.ajax in explicit references in our code.

I don't think this RFC is scoped for items, like collections, in backbone referenced in the main app. This would be a step forward in removing pieces of jQuery. If in the future we want to tackle the 'behind the scenes' http in backbone, we could always do something to this : https://github.com/jashkenas/backbone/blob/master/backbone.js#L1627

**Comment by al-the-x** [comment]
I fixed your Markdown.

I would recommend that we make a public API for `backbone.store` that is consistent and pass options to the library to configure it, isolating the consuming app from the complexity of instantiating the `Store` object and picking an adapter, something like:

```js
// in initializers/store.js
import Store from 'backbone.store';
import BackboneStoreAdapterExperiment from '@/utils/optimizely';

export default function initStore(app) {
  app.store = Store.instance({
    adapter: BackboneStoreAdapterExperiment.getVariantName(), // e.g. "$.ajax" or "fetch"
    headers: { // global headers
      'X-Client-Version': window.CLIENT_VERSION,
      'X-Style-Version': window.STYLE_VERSION
    },
    onBeforeRequest: modifyRequest, // named how you like
    // . . . other global settings . . .
  })
})
```

This ensures that `backbone.store` contains the responsibility of correctly instantiating the `Store` with a named `HttpAdapter` implementation, either `jQueryHttpAdapter` or `FetchHttpAdapter`, and consuming code -- like our app -- is only responsible for passing the configuration to the `Store` factory. (I don't care whether you call the method `instance` or `factory` or whatever, TBH).

Preserving the existing API, we might also expose an `ajax` or `http` or `request` method that uses whatever `HttpAdapter` is configured on the `Store` instance:

```js
// in route `/login`
const response = await app.store.ajax(url, {
  headers: { . . . },
  data,
});
```

This interface should be identical regardless of the adapter selected. That's the point of [an Adapter pattern](https://en.wikipedia.org/wiki/Adapter_pattern), after all: to normalize the interface differences of external interfaces with a unified common interface. Fundamentally, `$.ajax` is doing the same work as `fetch` just with different names and invocation logic.

By providing a common `ajax` / `http` / `fetch` / `request` method, code downstream from `initializers/store` knows and cares nothing about the active experiment. The `store` has been configured to use the appropriate `HttpAdapter`, and downstream code -- like the `/login` service -- can continue unchanged. When we eventually delete one branch of the experiment, either the `fetch` or `$.ajax` branch, the downstream code is unaffected; the experiment is confined to `initializers/store`. The only code that needs to change is a single line in `initializers/store`.

As for names, I don't care what they are.

**Comment by AtofStryker** [comment]
@al-the-x I like this method the best as it reduces complexity. 

I did want to mention that to make the api the same when making one of these methods public, will require changes to both adapters. So they can both have an `ajax`/ `http` (whatever we call it. I personally like `request`) method that can be invoked on the instance via adapter in the store. 

This would require for a version to be published of the jQueryAjaxAdapter to support the public method. I dont think the changes would be super involved but I do think it would be well worth it to reduce the complexity in the consuming app to follow the adapter pattern as opposed to dancing around it like I initially suggested.

And thank you for fixing my terribad markup =)

**Comment by al-the-x** [comment]
Yeah, that sounds pretty good: issue a release that intros `request` and the factory; update the app to use that API; add `HttpAdapterFetch` with an identical API; add the experiment to the app; spread that out over a couple weeks so we get metrics on each. Lovely n

**Comment by AtofStryker** [comment]
@JohnColanduoni @jessewagstaff @racoleman are there any additional items we want to cover here or is the strategy laid out by @al-the-x ok to proceed with?

**Comment by jessewagstaff** [comment]
I think the strategy is great. We just have to make sure that `await app.store.ajax(url)` does not include any of the default json-api style headers in the `Store` instance. Currently the headers `'Accept': 'application/vnd.api+json'` and `'Content-Type': 'application/vnd.api+json'` are baked into the `http-adapter` but must not be present for some legacy endpoints like `await app.store.ajax('/api/login/', {
  method: 'POST'
})`

**Comment by AtofStryker** [comment]
#65 is now open

**Pull request closed without merging**
